workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"      
      when: never
    - when: always

stages:
  - test

run_unit_tests:
  image: node:18-alpine3.16
  stage: test
  before_script:
    - npm install
  script:
    - npm test
