name: Deploy to AWS CloudFront
on:
  push:
    branches:
      - main
jobs: 
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '18'
        - run: npm install
        - run: npm run build
        - uses: actions/upload-artifact@v3.1.2
          with:
            # Artifact name
            name: built-app
            # A file, directory or wildcard pattern that describes what to upload
            path: dist
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3.1.2
        with:
          name: built-app
          path: dist
      - run: ls dist
            
        
